package nazenov.utils;

public class ChampionsNames {
    public static String[] championNames = {
            "Aatrox",
            "Ahri",
            "Akali",
            "Alistar",
            "Amumu",
            "Anivia",
            "Annie",
            "Aphelios",
            "Ashe",
            "AurelionSol",
            "Azir",
            "Bard",
            "Blitzcrank",
            "Brand",
            "Briar",
            "Braum",
            "Caitlyn",
            "Camille",
            "Cassiopeia",
            "ChoGath",
            "Corki",
            "Darius",
            "Diana",
            "DrMundo",
            "Draven",
            "Ekko",
            "Elise",
            "Evelynn",
            "Ezreal",
            "Fiddlesticks",
            "Fiora",
            "Fizz",
            "Galio",
            "Gangplank",
            "Garen",
            "Gnar",
            "Gragas",
            "Graves",
            "Gwen",
            "Hecarim",
            "Heimerdinger",
            "Illaoi",
            "Irelia",
            "Ivern",
            "Janna",
            "JarvanIV",
            "Jax",
            "Jayce",
            "Jhin",
            "Jinx",
            "KaiSa",
            "Kalista",
            "Karma",
            "Karthus",
            "Kassadin",
            "Katarina",
            "Kayle",
            "Kayn",
            "Kennen",
            "KhaZix",
            "Kindred",
            "Kled",
            "KogMaw",
            "LeBlanc",
            "LeeSin",
            "Leona",
            "Lillia",
            "Lissandra",
            "Lucian",
            "Lulu",
            "Lux",
            "Malphite",
            "Malzahar",
            "Maokai",
            "MasterYi",
            "MissFortune",
            "Mordekaiser",
            "Morgana",
            "Nami",
            "Nasus",
            "Nautilus",
            "Neeko",
            "Nidalee",
            "Nocturne",
            "NunuWillump",
            "Olaf",
            "Orianna",
            "Ornn",
            "Pantheon",
            "Poppy",
            "Pyke",
            "Qiyana",
            "Quinn",
            "Rakan",
            "Rammus",
            "RekSai",
            "Rell",
            "Renekton",
            "Rengar",
            "Riven",
            "Rumble",
            "Ryze",
            "Samira",
            "Sejuani",
            "Senna",
            "Seraphine",
            "Sett",
            "Shaco",
            "Shen",
            "Shyvana",
            "Singed",
            "Sion",
            "Sivir",
            "Skarner",
            "Sona",
            "Soraka",
            "Swain",
            "Sylas",
            "Syndra",
            "TahmKench",
            "Taliyah",
            "Talon",
            "Taric",
            "Teemo",
            "Thresh",
            "Tristana",
            "Trundle",
            "Tryndamere",
            "TwistedFate",
            "Twitch",
            "Udyr",
            "Urgot",
            "Varus",
            "Vayne",
            "Veigar",
            "VelKoz",
            "Vi",
            "Viego",
            "Viktor",
            "Vladimir",
            "Volibear",
            "Warwick",
            "Wukong",
            "Xayah",
            "Xerath",
            "XinZhao",
            "Yasuo",
            "Yone",
            "Yorick",
            "Yuumi",
            "Zac",
            "Zed",
            "Zeri",
            "Ziggs",
            "Zilean",
            "Zoe",
            "Zyra"
    };
    public static String[] lolItems = {
            "Abyssal Mask",
            "Adaptive Helm",
            "Aegis of the Legion",
            "Aether Wisp",
            "Amplifying Tome",
            "Archangel's Staff",
            "Ardent Censer",
            "Ardent Censer",
            "Athene's Unholy Grail",
            "B. F. Sword",
            "Bami's Cinder",
            "Berserker's Greaves",
            "Blade of the Ruined King",
            "Blasting Wand",
            "Bloodthirster",
            "Boots of Mobility",
            "Boots of Speed",
            "Boots of Swiftness",
            "Caulfield's Warhammer",
            "Chain Vest",
            "Chalice of Harmony",
            "Cloak of Agility",
            "Control Ward",
            "Corrupting Potion",
            "Cull",
            "Dagger",
            "Dead Man's Plate",
            "Death's Dance",
            "Doran's Blade",
            "Doran's Ring",
            "Doran's Shield",
            "Duskblade of Draktharr",
            "Edge of Night",
            "Elixir of Iron",
            "Elixir of Sorcery",
            "Elixir of Wrath",
            "Essence Reaver",
            "Executioner's Calling",
            "Eye of the Herald",
            "Eye of the Oasis",
            "Eye of the Watchers",
            "Face of the Mountain",
            "Faerie Charm",
            "Fiendish Codex",
            "Frostfang",
            "Frozen Heart",
            "Frozen Mallet",
            "Gargoyle Stoneplate",
            "Giant's Belt",
            "Glacial Shroud",
            "Guardian Angel",
            "Guinsoo's Rageblade",
            "Haunting Guise",
            "Health Potion",
            "Hexdrinker",
            "Hextech GLP-800",
            "Hextech Gunblade",
            "Hextech Protobelt-01",
            "Hextech Revolver",
            "Hextech Rocketbelt",
            "Hextech Sweeper",
            "Hunter's Machete",
            "Hunter's Potion",
            "Hunting Knife",
            "Iceborn Gauntlet",
            "Infinity Edge",
            "Ionian Boots of Lucidity",
            "Iron Elixir",
            "Jaurim's Fist",
            "Kindlegem",
            "Kircheis Shard",
            "Knight's Vow",
            "Last Whisper",
            "Liandry's Anguish",
            "Lich Bane",
            "Locket of the Iron Solari",
            "Long Sword",
            "Lord Dominik's Regards",
            "Lord Van Damm's Pillager",
            "Lost Chapter",
            "Manamune",
            "Manamune (Quick Charge)",
            "Maw of Malmortius",
            "Mejai's Soulstealer",
            "Mercurial Scimitar",
            "Mercury's Treads",
            "Mikaels Crucible",
            "Moonstone Renewer",
            "Mortal Reminder",
            "Nashor's Tooth",
            "Needlessly Large Rod",
            "Negatron Cloak",
            "Ninja Tabi",
            "Nomad's Medallion",
            "Null-Magic Mantle",
            "Oblivion Orb",
            "Oracle's Extract",
            "Pauldrons of Whiterock",
            "Phage",
            "Pickaxe",
            "Poacher's Dirk",
            "Prospector's Blade",
            "Prospector's Ring",
            "Prospector's Shield",
            "Protector's Vow",
            "Quicksilver Sash",
            "Rabadon's Deathcap",
            "Rapid Firecannon",
            "Ravenous Hydra",
            "Recurve Bow",
            "Redemption",
            "Refillable Potion",
            "Reliquary of the Golden Dawn",
            "Remnant of the Ascended",
            "Remnant of the Aspect",
            "Remnant of the Watchers",
            "Requiem Scepter",
            "Retribution",
            "Runesteel Spaulders",
            "Runesteel Shoulderguards",
            "Runesteel Greaves",
            "Sanguine Blade",
            "Sapphire Crystal",
            "Serrated Dirk",
            "Seraph's Embrace",
            "Seraph's Embrace (Quick Charge)",
            "Serylda's Grudge",
            "Serrated Dirk",
            "Sheen",
            "Shurelya's Battlesong",
            "Silvermere Dawn",
            "Silver Serpents",
            "Spectral Sickle",
            "Spellthief's Edge",
            "Spirit Blossom",
            "Spirit Blossom Thresh's",
            "Spectre's Cowl",
            "Stalker's Blade",
            "Statikk Shiv",
            "Sterak's Gage",
            "Stormrazor",
            "Sunfire Aegis",
            "Sunfire Enchant",
            "Sunfire Cape",
            "Sunfire Aegis",
            "Sunfire Enchant",
            "Supercharged Collection",
            "Sweeping Lens (Trinket)",
            "Targon's Buckler",
            "Tear of the Goddess",
            "Tear of the Goddess (Quick Charge)",
            "The Collector",
            "The Golden Dawn",
            "The Showstopper",
            "The Trickster",
            "Thornmail",
            "Titanic Hydra",
            "Trinity Force",
            "Turbocharged Hexperiment",
            "Umbral Glaive",
            "Vampiric Scepter",
            "Vespertide",
            "Vespertide (Quick Charge)",
            "Void Staff",
            "Warden's Mail",
            "Warmog's Armor",
            "Watchful Wardstone",
            "Weighted Storage Cube",
            "Winged Moonplate",
            "Wit's End",
            "Youmuu's Ghostblade",
            "Zeal",
            "Zekes Convergence",
            "Zhonya's Hourglass",
            "Zhonya's Paradox",
            "Zhonya's Paradox",
            "Zyanya's Dominance",
            "Zyanya's Embrace",
            "Zyanya's Paradox",
    };

}

